name: coverage

on:
  push:
    branches: [main]

jobs:
  unit:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
    - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
      with:
        go-version-file: 'go.mod'
    - uses: brokeyourbike/go-mockery-action@1e10ac1068b2410b26cccafa5c345a7f21bd758c # v0.2
      with:
        mockery-version: '2.53.6'
    - run: make mock
    - run: go install gotest.tools/gotestsum@v1.13.0 
    - run: gotestsum --junitfile junit.xml -- -race -covermode=atomic -coverprofile=coverage.out -v ./...

    - uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.out
    - uses: codecov/test-results-action@0fa95f0e1eeaafde2c782583b36b28ad0d8c77d3 # v1
      if: ${{ !cancelled() }}
      with:
        token: ${{ secrets.CODECOV_TOKEN }}